### ISSUE TITLE
debug recent failures

### ISSUE THREAD

**Issue by boneskull** [boneskull/alfred-npms#1]
Recently, I've had problems getting any data for some modules (`request` being one of them).  WTF?

**Comment by kennethkoontz** [comment]
Have you tried restarting your computer?

**Comment by boneskull** [comment]
@kennethkoontz have you tried stfu???

**Comment by boneskull** [comment]
I think I probably solved this bug with the latest fix anyway

**Comment by kennethkoontz** [comment]
LOL!

Ken Koontz

On Wed, Nov 02, 2016 at 1:51 AM Christopher Hiller

<
mailto:Christopher Hiller notifications@github.com

> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Closed
https://github.com/boneskull/alfred-npms/issues/1
.

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/boneskull/alfred-npms/issues/1#event-844557990
, or
